# Generated by Django 5.0.4 on 2024-08-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0003_filesystem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
