# Generated by Django 5.0.4 on 2024-08-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0004_filesystem_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesystem',
            name='filesize',
        ),
    ]
