# Generated by Django 5.0.4 on 2024-08-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0005_remove_filesystem_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='filesize',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
